# Generated by Django 2.1.2 on 2018-11-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooSpam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoospamform',
            name='email_recipient',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
